### ISSUE TITLE
Use all parents of textnode

### ISSUE THREAD

**Issue by skruse** [goose3/goose3#101]
Extraction "fails" for the following website as only the parent and parentparent get a score:
https://www.wiwo.de/unternehmen/industrie/linde-gasekonzern-muss-teile-des-us-geschaefts-verkaufen/19562798.html
It will only retrieve one of the "p" blocks (usually the one with the most words) while ignoring the common ancestor of all "p" blocks.

Is there a reason why not all parents get a score? I adapted`'calculate_best_node` to increase score for all parents by `upscore * 2/(depth+1)` which succeeds in extraction of the mentioned site, while not changing too much.

**Comment by dlrobertson** [comment]
👍 can you post a PR? Sounds interesting.

**Comment by skruse** [comment]
Just did here: https://github.com/skruse/goose3/pull/1

**Comment by dlrobertson** [comment]
If you're willing to post it to the upstream repo it might be something worth merging https://github.com/goose3/goose3/compare/master...skruse:update_score_all_parents

**Comment by dlrobertson** [comment]
This can be closed now right?

**Comment by barrust** [comment]
I believe so, I will close now!

**Comment by skruse** [comment]
Thanks!
