### ISSUE TITLE
How do I extract text from a string instead of url

### ISSUE THREAD

**Issue by Freakwill** [goose3/goose3#104]
How do I extract text from a string instead of url?

I did not find the api.

**Comment by dlrobertson** [comment]
If I'm understanding you correctly, something like the following should work.

```python
>>> from goose3 import Goose
>>> raw_html = '<html><body>Hello, World!</body></html>'
>>> g = Goose()
>>> article = g.extract(raw_html=raw_html)
```

**Comment by Freakwill** [comment]
Yes, it is what I want. I think that it should work with  plain text, like another summarization tool `sumy`.

**Comment by barrust** [comment]
Yes, that is how you pull from an html string. Per the docs: [Goose.extract](https://goose3.readthedocs.io/en/latest/code.html#goose3.Goose.extract)
