### ISSUE TITLE
Remove footnote markers

### ISSUE THREAD

**Issue by roniemartinez** [goose3/goose3#105]
Currently, footnote numerals are not cleaned up. For example, on Wikipedia articles, citations are often left like [1], [2], [a], etc.

BTW, great library! I am currently using it. Thanks!

**Comment by barrust** [comment]
Can you provide an example? What would you be expecting instead?

**Comment by roniemartinez** [comment]
Wikipedia is the best example. Try to extract an article and you'll see the texts/numbers left by footnotes.

**Comment by barrust** [comment]
For Wikipedia, I would use a wikipedia library such as [pymediawiki](https://github.com/barrust/mediawiki). It will allow you to pull the content from a mediawiki site without the references, etc. 

In full disclosure, I maintain that package.

**Comment by roniemartinez** [comment]
I am familiar with it. However, it is not universal as I cannot use it in other sites that has similar issues with footnotes. Wikipedia is just one of the examples with this issue.

**Comment by barrust** [comment]
OK, understood! Unfortunately I do not have time at the moment to work on this but PRs are always welcome!

**Comment by Nimit-Khurana** [comment]
#105
`if self.config.parse_lists:
            # Split out the lists and clean them up! Ensuring no trailing spaces
            txt = text.replace('\n•', '•').split('• ')
            txt = [x.strip() for x in txt]

            if self.config.pretty_lists:
                #text = '\n• '.join(txt)
                # wikipedia citations
                text = re.sub("\[\d\]","", '\n'.join(txt))
            else:
                #text = '\n'.join(txt)
                # wikipedia citations
                text = re.sub("\[\d\]","", '\n'.join(txt))
        return text`
Is this method workable? 
I just used re module.

**Comment by roniemartinez** [comment]
Hi @Nimit-Khurana 

Wikipedia footnote markers may include letters or even words: https://en.wikipedia.org/wiki/Help:Footnotes#Overview

**Comment by Nimit-Khurana** [comment]
@roniemartinez
 I checked the output for cleaned_text and all the footnotes in raw_html are converted to string(eg. [1])
I can think of sending the raw_html in crawl method to remove the <sup> tags.
Will this be ok??

**Comment by roniemartinez** [comment]
Hi @Nimit-Khurana 

That will be okay as long as there will be no footnote markers in the cleaned_html.

**Comment by roniemartinez** [comment]
Hi @Nimit-Khurana 

I wonder of Maintainers are looking at your PR. There are failing tests/checks though but I do not think they were from yours.

**Comment by barrust** [comment]
The failing tests are actually due to this PR  because in many cases the user wants the footnotes, etc. Perhaps a config option could be added to remove the `sup` tag could be added but really, it shouldn't remove it from the `raw_html` element and should be done later in the process. I will make comments in the PR also.
