### ISSUE TITLE
How to pass operating system information 

### ISSUE THREAD

**Issue by sanjeev9939** [goose3/goose3#107]
I want to pass operating system information in the script and cookies information in goose3. so that we can handle HTTP error 403 : Forbidden. Could anyone help me

**Comment by barrust** [comment]
Right now, we do not have a method to pass cookies to sites. We can add it, but it would be a manual configuration. 

``` python
from goose import Goose

config = {'http_cookies': {}}  # your cookies would be here...
with Goose(config) as g:
   a = g.extract(url="...")
```

Is that what you are thinking?

**Comment by sanjeev9939** [comment]
I have already tried it,  I need help in handling HTTP error 403: Forbidden  for thehindu.com and thehundubusinessline.com, please help me in resolving this error

**Comment by TomJamesPearce** [comment]
Hi @sanjeev9939 The easiest way to set your cookies would be to simply use the requests library yourself, and then pass the returned HTML into Goose


```
import requests
from goose3 import Goose

jar = requests.cookies.RequestsCookieJar()
jar.set('tasty_cookie', 'yum', domain='httpbin.org', path='/cookies')
ar.set('gross_cookie', 'blech', domain='httpbin.org', path='/elsewhere')
url = 'https://www.thehindu.com/sci-tech/science/india-to-have-a-separate-space-station-isro/article27898707.ece?homepage=true'
r = requests.get(url, cookies=jar)

with Goose() as g:
   a = g.extract(raw_html=r.text)
```

For what it's worth, I tried scraping thehundu.com (only one page) and had no problems.
Maybe they are blocking you for making too many requests?
If that were the case, I'd suggest either spacing out your requests, or looking into proxies.

Also, if you haven't already; modifying your user agent would be what I tried before bothering with cookies.
