### ISSUE TITLE
config.known_publish_date_tags Fails 

### ISSUE THREAD

**Issue by Yanyul** [goose3/goose3#113]
When trying to apply a customized publish_date_tags for HTML extraction, it failed hard.

This could be one of the reasons why the code never gets to what I added to the known_publish_date_tags. However, when I commented out the two if statements locally, it still gave me the 'default' article:published_time as the publish date output.

```
class PublishDateExtractor(BaseExtractor):
    def extract(self):
        # check the opengraph and ReportageNewsArticle dictionary for the
        # publication date first.
        if "article:published_time" in self.article.opengraph:
            return self.article.opengraph["article:published_time"]
        if self.article.schema and "datePublished" in self.article.schema:
            return self.article.schema["datePublished"]
```

**Comment by barrust** [comment]
So can you explain to me what you mean by "fails hard"? If the article has an opengraph date than that should be the "best" date to return. 
As for when you commented out the two if statements, I am unsure how that would have returned that date as it doesn't use the opengraph data to pull it out unless that if statement is present. Perhaps there was an issue with using your local copy of the code? 

To be able to help more, I would need an example of what you are attempting, including the new pattern to add and the url you are trying to parse.

**Comment by Yanyul** [comment]
> So can you explain to me what you mean by "fails hard"? If the article has an opengraph date than that should be the "best" date to return.
> As for when you commented out the two if statements, I am unsure how that would have returned that date as it doesn't use the opengraph data to pull it out unless that if statement is present. Perhaps there was an issue with using your local copy of the code?
> 
> To be able to help more, I would need an example of what you are attempting, including the new pattern to add and the url you are trying to parse.


Thank you for the quick follow-up! :)

This basically means that the scrapper skips any user-customized PublishDatePattern, if the opengraph has a pushlished_time available, and it will never get to extract the date pattern that users added. 

I tried both 
`config.known_publish_date_tags = PublishDatePattern(attr = "property", value = "article:modified_time", content = 'content')`
`config._known_publish_date_tags = PublishDatePattern(attr = "property", value = "article:modified_time", content = 'content')`
No matter what I added, the undesired published_time was returned.

**Comment by barrust** [comment]
Generally the `opengraph` data is the most correct data. If you can think of a good way to see if there are user described values and handle those first, I would be open to any Pull Requests. Unfortunately, I do not have time to work much on this project but am happy to help as much as I can.

**Comment by barrust** [comment]
@Yanyul can you provide an example URL that I can look at about this issue? I may have an idea on how it could be resolved. Thanks!

**Comment by barrust** [comment]
So it looks like the modified time that you are looking for is in the opengraph data (see code example below). 

With the data here, that could be everything you need, or, perhaps, a modified_date could be added as a property of the article. Besides in the opengraph data, I am unsure of other methods to find the modified time. 

Thoughts? 

``` python
url='https://www.draysbay.com/2021/2/18/22289391/predicting-rays-opening-day-roster-2021'
with Goose() as goose:
    article = goose.extract(url=url)
    print(article.opengraph)  # all the opengraph data
    print(article.opengraph.get("article:modified_time"))  # a string of the modified time

```

**Comment by barrust** [comment]
closing as the modified time is provided in opengraph data.
