### ISSUE TITLE
Can't extract title with article.title, gives empty string. 

### ISSUE THREAD

**Issue by Pradhvan** [goose3/goose3#116]
Hey 👋🏾 

I am trying to extract the title from a given URL but the title is given as an empty string. I parsed the raw HTML with BeautifulSoup to check if the article title is present or not. It seems to work with BS4 but not with goose3: 

BeautifulSoup Example:

```python
from urllib.request import urlopen
from bs4 import BeautifulSoup
url='https://pradhvan.scrollstack.com/' 
html = urlopen(url)
soup = BeautifulSoup(html, 'lxml')
print(soup.title.string) 
# Output -> Pradhvan
```

goose3 example

```python
from goose3 import Goose
from requests import get
url='https://pradhvan.scrollstack.com/' 
response = get(url)
extractor = Goose()
article = extractor.extract(raw_html=response.content)
print(article.title)
```
It would be really helpful if you folks check if it's a bug or am I doing something wrong?  Thank you 😄

**Comment by barrust** [comment]
Doing some quick diagnostics it looks like this is happening because in the opengraph the title for this page is the same as the site name. Generally, the library removes the site name from the title. I think a change like the following would fix this issue for you. 

`goose3/extractors/title.py`
```python
# original code
if "site_name" in list(self.article.opengraph.keys()): 
    site_name = self.article.opengraph['site_name']
    # remove the site name from title
    title = title.replace(site_name, '').strip()
```

```python
# revised code
if "site_name" in list(self.article.opengraph.keys()) and self.article.opengraph['site_name'] != title: 
    site_name = self.article.opengraph['site_name']
    # remove the site name from title
    title = title.replace(site_name, '').strip()
```

This would keep the title in this case but still clean up the title in cases where the site name is appended to the title.

**Comment by Pradhvan** [comment]
@barrust I am happy to do a PR 😄

**Comment by barrust** [comment]
PRs are ALWAYS welcome!

**Comment by Pradhvan** [comment]
@barrust should I also create an additional test in the `test/test_title.py`? Replicating the same issue when:

>it looks like this is happening because in the opengraph the title for this page is the same as the site name.

**Comment by barrust** [comment]
If you can, that would be great! If it doesn't make sense, I should be able to help after the PR is merged.

**Comment by Pradhvan** [comment]
Let me try to figure out how can I add a test for it, if everything works out that would be great. Otherwise will add a test after the PR is merged with your help.

**Comment by Pradhvan** [comment]
@barrust created a PR with the patch. Please review whenever you are free. 😄 

Checking how can I add a unit test for the patch.

**Comment by barrust** [comment]
To add tests takes a few files to be added; I will create a branch to add a test and @ you on the PR. Thanks for taking this on!

**Comment by Pradhvan** [comment]
@barrust that would be great :)
