### ISSUE TITLE
Why when I use top_image I always get None

### ISSUE THREAD

**Issue by ArturasDruteika** [goose3/goose3#120]
Is it error or I do something wrong, every time I try to use article.top_image it return None. No matter what url I pass it is always the same.

**Comment by barrust** [comment]
Can you provide an example URL that is failing? Also a code sample of how you configured goose3 would be helpful. 

According to the docs, you need to enable image fetching (it can take awhile) or it will always be `None`.

``` python
from goose3 import Goose3

with Goose3({'enable_image_fetching': True}) as g:  # include pulling images
    article = g.extract(my_url)
    print(article.top_image) # or whatever you want to do with it
```
The docs might need to be updated in the Article section to mention that it has to be enabled in the configuration.

**Comment by ArturasDruteika** [comment]
As for url I pass articles from cnn, nytimes other news outlets articles but still, it always returns None. 
url = 'https://10ways.com/improve-yourself/10-ways-to-improve-your-sleep-so-the-following-day-youre-more-productive/13262'

    goose = Goose()

    article_goose = goose.extract(url)
    print(article_goose.top_image)

**Comment by ArturasDruteika** [comment]
Solved this issue

    from goose3 import Goose, Configuration
    
    url = 'https://10ways.com/save/how-to-save-money-on-the-philips-perfect-draft-system-beer-kegs-includes-beerhawk/12878'

    config = Configuration()
    config.enable_image_fetching = True

    g = Goose(config)
    article_goose = g.extract(url)

Thank you very much for directing me to look for enabling this feature.

**Comment by barrust** [comment]
Glad to help and good luck!
