### ISSUE TITLE
FIPS issue on Rocky Linux

### ISSUE THREAD

**Issue by openbrian** [goose3/goose3#133]
goose3 is not working in a FIPS environment due to md5.

Jan 17 21:19:13 aj.e.n.o service.sh[1931118]:     link_hash = '%s.%s' % (hashlib.md5(raw_html).hexdigest(), time.time())
Jan 17 21:19:13 aj.e.n.o service.sh[1931118]: ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS

I'll submit a PR to change to sha1.  This works.

**Comment by barrust** [comment]
That is interesting that it is complaining about the md5sum. It is used not in a true cryptographic sense but more to ensure that we don't download the same files and ensure that they have unique names. 

A PR with a change to resolve this works for me!
