### ISSUE TITLE
unwanted dependency (jieba)

### ISSUE THREAD

**Issue by efremsternbach** [goose3/goose3#141]
We use goose as part of our AWS Serverless code. There is a code limit of around 80M for deployment of an AWS Lambda. When deploying recently I ran in to a problem since pip for goose downloads a dependency jieba which apparently is a Chinese language module. This module is 36M! It eats around half my deployment limit for something I don't even want to use. 

Aside from doing a manual packaging of my lambda is there any way to tell AWS sam or pip to exclude the unwanted package? I feel strongly that something this large should be a separate install and not a direct dependency.  Why would you require this module when it's huge and most people won't even use it?

Any help would be appreciated.

**Comment by barrust** [comment]
I believe there is a way to add an optional dependency; any help setting it up (PR, etc) to make that possible to remove would be appreciated!

**Comment by lababidi** [comment]
This is a fair request! We could make the module optional. Feel free to
make a PR that allows a "cn" to be passed in the pip install to include it.
