### ISSUE TITLE
Support for the "@graph" keyword in the linked data json node "application/ld+json"

### ISSUE THREAD

**Issue by julianofnascimento** [goose3/goose3#167]
Hi, I just started using this lib for a crawler that I'm building. Noticed the lack of support for the "@graph" keyword in the linked data nodes (application/ld+json). Some of the news websites use this structure for linked data nodes: {"@context":"https://schema.org","@graph":[{"@type":"...", ...}, {"@type":"...", ...}]}. I will submit a pull request for this :)

**Comment by barrust** [comment]
closed!

Thank you for the PR!
