### ISSUE TITLE
Missing heading data

### ISSUE THREAD

**Issue by Eddies101** [goose3/goose3#17]
Hi,  I've been trying to extract text from some sites.  The following may be an issue or a feature.  I'm new to programming and python so not quite sure

I'm finding that the extract is missing heading and list data.
For example - [http://bouncebackhigher.com/articles/empathy-a-critical-skill-for-effective-leadership/](http://bouncebackhigher.com/articles/empathy-a-critical-skill-for-effective-leadership/)
The headings What is Empathy? and  What are the Traits of an Empathetic, Effective Leader? don't appear in the clean text. Text in lists also doesn't seem to extract. The headings are useful markers splitting the text,

**Comment by barrust** [comment]
@Eddies101 I agree that those would be useful items to extract. I haven't had the time recently to look into why lists and headings are not being extracted. Any help would be greatly appreciated!

**Comment by abs51295** [comment]
@barrust I also see that even the current implementation doesn't handle lists and headings well. Any updates on this?

**Comment by barrust** [comment]
@abs51295 I haven't had time to look into this; any help would be appreciated!

**Comment by abs51295** [comment]
Sure @barrust I would like to contribute to this! Any pointers to get started or where to look at? Thanks :)

**Comment by Eddies101** [comment]
In crawler.py
The problem seem to come in
self.article.cleaned_text = self.formatter.get_formatted_text()   (around line 198)

The raw html (self.article.top_node) before going into this function seems fine but the return from the function seems to be have no list data.

I hope this helps

**Comment by barrust** [comment]
Merged the ability to pull in #52
