### ISSUE TITLE
schema graph error

### ISSUE THREAD

**Issue by adonisnafeh** [goose3/goose3#202]
Failure when handling a schema graph dictionary

```
g = Goose()
g.extract('https://www.iphonelife.com/content/apple-watch-ecg-not-working')
```

> goose3/crawler.py", line 153, in process
>     self.article._schema = self.schema_extractor.extract()
> goose3/extractors/schema.py", line 35, in extract
>     if "@type" in linked_data and linked_data["@type"] in KNOWN_SCHEMA_TYPES:
> TypeError: string indices must be integers

In `SchemaExtractor.__parse_linked_data_nodes` if `@graph` is found in content, `linked_data` is extended with the names of the graph keys not the graph dict.

```

    if isinstance(content, list):
        linked_data.extend(
            [context for context in content if self.__validate_context(context)])
    elif isinstance(content, dict) and self.__validate_context(content):
        if "@graph" in content:
            linked_data.extend(content["@graph"])
        else:
            linked_data.append(content)
```

But in `SchemaExtractor.extract` `linked_data_nodes` is expected to be a list of dicts. 

```
for linked_data in linked_data_nodes:
    if "@type" in linked_data and linked_data["@type"] in KNOWN_SCHEMA_TYPES:
        return linked_data
```

changing  `linked_data.extend(content["@graph"])` to ` linked_data.append(content["@graph"])` works but calling `.extend `might have been intended for other cases.

**Comment by barrust** [comment]
If I remember correctly, there is a reason that it needs to also use the extend since there are some that the "@graph" points to a list of objects. Perhaps something like the following would allow for both options to continue to work

`goose3/extractors/schema.py` around line 44:
```python
if isinstance(content, list):
    linked_data.extend([context for context in content if self.__validate_context(context)])
elif isinstance(content, dict) and self.__validate_context(content):
    if "@graph" in content and isinstance(content["@graph"], list):
        linked_data.extend(content["@graph"])
    elif "@graph" in content:
        linked_data.append(content["@graph"])
    else:
        linked_data.append(content)
```

**Comment by adonisnafeh** [comment]
lgtm
