### ISSUE TITLE
Cleaned HTML?

### ISSUE THREAD

**Issue by Jwink3101** [goose3/goose3#26]
using `article.cleaned_text`, I get a nice text description, but it (a) lacks enumerated and bulleted lists and (b) removes images.

It would be really great to have a cleaned article view that contains the HTML of the main text (which clearly goose can find) but still contain the basic HTML. 

or, is this possible and I am missing it?

**Comment by lababidi** [comment]
I'm sure it's possible. It's a good idea.

I would love the help in at least exploring the goose code to see how/where
it can be done.
Wanna give it a shot?

**Comment by barrust** [comment]
`article.cleaned_text` is the text of the article. You are correct that, at the moment it removes any lists. For the dom element that is what is used, you may want to look at `article.top_node` 

The code documentation for `top_node` says: 
``` python
# holds the top Element we think
# is a candidate for the main body of the article
```

See if that is what you are looking for!

**Comment by Jwink3101** [comment]
@barrust, that certainly seems promising. Sadly, with despite a lot of playing (and object introspection) have I not found how to extract the HTML from that top element!

Thanks for the help though...

**Comment by barrust** [comment]
I believe it is an lxml etree element so perhaps something like this would do it:

``` python
from lxml import etree

# get article, etc

print(etree.tostring(article.top_node, pretty_print=True))

```

http://lxml.de/tutorial.html

**Comment by Enkerli** [comment]
Maybe it could also become an option to only parse plain text, in `.extract()`?
The fact that Goose is somehow doing something with images doesn’t sound like a particularly good idea if we just want to work with the plain text (say, for topic modelling). It might even be the part [giving me errors](https://github.com/goose3/goose3/issues/31).

**Comment by barrust** [comment]
@Enkerli You can turn off the image processing by setting the configuration when setting up goose. 

``` python
from goose3 import Goose

g = Goose({'enable_image_fetching': False}

g.extract(url)  # will no longer attempt to pull the top image

```

Hopefully these options will be easier to trace once we have online documentation (#30) is completed

**Comment by barrust** [comment]
So we are in the process of getting automated documentation builds completed for [goose3 on read the docs](http://goose3.readthedocs.io/en/latest/). 

You can find some documentation about setting config options in the [quickstart](http://goose3.readthedocs.io/en/latest/quickstart.html)

Hopefully what is there now will be helpful. If there are gaps (and I know there are gaps so other points of view are always helpful/welcome!) please let us know.
