### ISSUE TITLE
Several installing issue(I have fixed)

### ISSUE THREAD

**Issue by IdiotYcw** [goose3/goose3#3]
Today, when i tried to use the goose package developed by grangier, finally i found it doesnt support python 3.x. So i found this package.
1. i have to say the man who rename the package and main directory to goose3 is careless.
At line 30 in file `setup.py`, 
`version = load_source("version", os.path.join("goose", "version.py"))` 
should be 
`version = load_source("version", os.path.join("goose3", "version.py"))`
2. The similar error happens in MANIFEST.in then the first 2 lines 
`recursive-include goose/resources/images *
recursive-include goose/resources/text *` 
should be 
`recursive-include goose3/resources/images *
recursive-include goose3/resources/text` *`
3. When i tried to import this package, the console turned out `no module named goose3.utils`. So i supposed to add
`recursive-include goose3/extractors *
recursive-include goose3/utils *`
into MANIFEST.in sequencely at the end

After i changed the code above, it works!

**Comment by lababidi** [comment]
Thank you! would you like to submit a Pull Request and I will merge it in?

**Comment by lababidi** [comment]
@IdiotYcw Thanks for your issue. I've updated the package.
