### ISSUE TITLE
Online Documentation

### ISSUE THREAD

**Issue by barrust** [goose3/goose3#30]
While working with goose before participating in the development of goose3, I found that the documentation is lacking. Currently, the only documentation is the README file. Unfortunately, this does not contain all the information about how to configure goose. 

There are a few options: 

- Use something like [sphinx autodocs](http://www.sphinx-doc.org/en/stable/) that can then be uploaded to [readthedocs](https://readthedocs.org/) and can use the doc-string to automatically build the documentation 
- [MkDocs](http://www.mkdocs.org/) can also be uploaded to [readthedocs](https://readthedocs.org/). 
- Hard coded HTML files

Thoughts and comments would be great. I am happy to help start the documentation if others find this to be helpful.

**Comment by lababidi** [comment]
I think having some sort of idea as to what functions methods and objects
we want "exposed" to the user is the first step and then we can embark on
how to document. At that point in for the easiest solution that is
available.

**Comment by barrust** [comment]
At a minimum, I think the `Goose` and `Configuration` objects are the bare minimum. If we decide to expose more of the inner workings then we can. What do you think of that?

**Comment by lababidi** [comment]
That's perfect. Beyond that, I have no clue what the best documentation
system is these days. I can dig that up if you'd like, but I'm sensing
something that converts the doc to some sort of githubio or readthedocs
should be fine. https://github.com/Syntaf/travis-sphinx seems like a good
solution

**Comment by barrust** [comment]
I have used sphinx in the past. We can use it to pull doc-strings from specific objects. I can start some docs in the coming days and put in a PR. We can tweak the wording easily enough. I know you can get sphinx and travis to play nice, but I haven't done that yet on my other projects.

**Comment by barrust** [comment]
@lababidi To be more clear, you can have readthedocs pull the documentation for you from github so we wouldn't have to do anything after setting it up.

**Comment by barrust** [comment]
@lababidi Let me know if you have issues setting up read the docs. I think I can set it up under my username if you'd rather me do it.

**Comment by lababidi** [comment]
Feel free to set it up. Thank you.

**Comment by barrust** [comment]
We now have documentation on read the docs! 

http://goose3.readthedocs.io/en/latest/

To get it fully setup to rebuild on every commit to master, we will need to setup a webhook in github to push. I do not have access to the settings of the repo to set this part up.

**Comment by lababidi** [comment]
You are now Admin @barrust

**Comment by barrust** [comment]
Thanks, I added the webhook. We will know the next time we make a change if everything is ok. I plan on releasing a new version sometime soon. If so, we will have updated documentation for that release.

**Comment by barrust** [comment]
@lababidi Things look good on the documentation setup. It builds the latest version each time we commit to master. It will also build versions that are tagged.
