### ISSUE TITLE
Strange Behaviour from `known_context_patterns`

### ISSUE THREAD

**Issue by Enkerli** [goose3/goose3#31]
As per an exchange with @barrust on a [Python-Goose issue](https://github.com/grangier/python-goose/issues/270) (in Python2), here’s a strange issue from using `known_context_patterns` in goose3 (Python3 on Anaconda for Windows 7, 64bit, on a ThinkPad).

This code fails, and throws a 404 (traceback at the end):
````
from goose3 import Goose
g = Goose()
# g.config.known_context_patterns = {'attr': 'class', 'value': 'datos_caso'}
# g.config.known_context_patterns = {'attr': 'class', 'value': 'pr-xs-20'}
article = g.extract(url='http://www.incyde.org/casos-exito/1')
print(article.cleaned_text)
````

Uncommenting line 3, it produces this (which isn’t too far from the appropriate result):

> Programa de "Tengo una Idea" (UCAM - 2015)
> Programa de "Social Media Networker" (UCAM - 2015)

Sounds weird that the `known_context_patterns` would make such a difference. Guess part of the difference is that, when the parser isn’t specifically searching for `datos_caso`, it trips over an image, maybe?

Other pages from the same site produce different results (can’t find a class to consistently get results from those). For instance, the root of that same path (`http://www.incyde.org/casos-exito`) produces appropriate results using the pattern in line 4 (`g.config.known_context_patterns = {'attr': 'class', 'value': 'pr-xs-20'}`):

> "Desde que entré en el programa de formación de Fundación Incyde y El ITM de Murcia para emprendedores, todo ha resultado mucho más fácil. He recibido formación de profesionales del sector del marketing online que han sido muy productivos 

...

Without the patterns, it has issues with cookies:

>Uso de cookies: Utilizamos cookies propias y de terceros para mejorar su experiencia y nuestros servicios, analizando la navegación en nuestro sitio web. Si continua navegando, consideramos que acepta su uso. Puede obtener más información en nuestra política de cookies.

Applying both patterns to individual pages (`http://www.incyde.org/casos-exito/1`) produces the same 404.

More specifically, this:
````
from goose3 import Goose
g = Goose()
g.config.known_context_patterns = {'attr': 'class', 'value': 'datos_caso'}
g.config.known_context_patterns = {'attr': 'class', 'value': 'pr-xs-20'}
article = g.extract(url='http://www.incyde.org/casos-exito/1')
print(article.cleaned_text)
````

produces the same Traceback as this:
````
from goose3 import Goose
g = Goose()
# g.config.known_context_patterns = {'attr': 'class', 'value': 'datos_caso'}
# g.config.known_context_patterns = {'attr': 'class', 'value': 'pr-xs-20'}
article = g.extract(url='http://www.incyde.org/casos-exito/1')
print(article.cleaned_text)
````

But this works:
````
from goose3 import Goose
g = Goose()
g.config.known_context_patterns = {'attr': 'class', 'value': 'datos_caso'}
# g.config.known_context_patterns = {'attr': 'class', 'value': 'pr-xs-20'}
article = g.extract(url='http://www.incyde.org/casos-exito/1')
print(article.cleaned_text)
````

The traceback:
````
Traceback (most recent call last):
  File "incydecasos1.py", line 5, in <module>
    article = g.extract(url='http://www.incyde.org/casos-exito/1')
  File "<PATH>\conda3\lib\site-packages\goose3\__init__.py", line
 100, in extract
    return self.crawl(cc)
  File "<PATH>\conda3\lib\site-packages\goose3\__init__.py", line
 112, in crawl
    article = crawler.crawl(crawl_candidate)
  File "<PATH>\conda3\lib\site-packages\goose3\crawler.py", line
123, in crawl
    return self.process(raw_html, parse_candidate.url, parse_candidate.link_hash
)
  File "<PATH>\conda3\lib\site-packages\goose3\crawler.py", line
193, in process
    self.get_image()
  File "<PATH>\conda3\lib\site-packages\goose3\crawler.py", line
215, in get_image
    self.article.top_image = self.image_extractor.get_best_image(doc, top_node)
  File "<PATH>\conda3\lib\site-packages\goose3\extractors\images.
py", line 75, in get_best_image
    image = self.check_large_images(topNode, 0, 0)
  File "<PATH>\conda3\lib\site-packages\goose3\extractors\images.
py", line 109, in check_large_images
    good_images = self.get_image_candidates(node)
  File "<PATH>\conda3\lib\site-packages\goose3\extractors\images.
py", line 271, in get_image_candidates
    good_images = self.get_images_bytesize_match(filtered_images)
  File "<PATH>\conda3\lib\site-packages\goose3\extractors\images.
py", line 288, in get_images_bytesize_match
    local_image = self.get_local_image(src)
  File "<PATH>\conda3\lib\site-packages\goose3\extractors\images.
py", line 331, in get_local_image
    return ImageUtils.store_image(self.fetcher, self.article.link_hash, src, sel
f.config)
  File "<PATH>\conda3\lib\site-packages\goose3\utils\images.py",
line 74, in store_image
    data = http_client.fetch(src)
  File "<PATH>\conda3\lib\site-packages\goose3\network.py", line
62, in fetch
    raise NetworkError(response.status_code, response.reason)
goose3.network.NetworkError: NetworkError: status code: Not Found; reason: 404
````

**Comment by Enkerli** [comment]
The thlot pickens.

This runs in python-goose (Py2):
````
from goose import Goose
g=Goose()
article=g.extract('https://cyberwales.net/clusters/')
print(article.cleaned_text)
````
The result is empty, but it throws no error. Running `g.extract('https://cyberwales.net/clusters/')` in interactive mode gives me:

> <goose.article.Article object at 0x000000000370E780>

But then, the same code in Goose3
````
from goose3 import Goose
g=Goose()
article=g.extract('https://cyberwales.net/clusters/')
print(article.cleaned_text)
````
Gives me this traceback:

````
Traceback (most recent call last):
  File "welshclusters.py", line 3, in <module>
    article=g.extract('https://cyberwales.net/clusters/')
  File "<PATH>\conda3\lib\site-packages\goose3\__init__.py", lin
 100, in extract
    return self.crawl(cc)
  File "<PATH>\conda3\lib\site-packages\goose3\__init__.py", lin
 112, in crawl
    article = crawler.crawl(crawl_candidate)
  File "<PATH>\conda3\lib\site-packages\goose3\crawler.py", line
118, in crawl
    raw_html = self.get_html(crawl_candidate, parse_candidate)
  File "<PATH>\conda3\lib\site-packages\goose3\crawler.py", line
224, in get_html
    html = self.fetcher.fetch(parsing_candidate.url)
  File "<PATH>\conda3\lib\site-packages\goose3\network.py", line
62, in fetch
    raise NetworkError(response.status_code, response.reason)
goose3.network.NetworkError: NetworkError: status code: Not Found; reason: 404
````
(Unlike the Incyde case, it’s not about parsing images.)

My naïve gut feeling is that it might have to do with newlines? Tried parsing a few things in Goose3 which had a better time after stripping `\r` and `\n` from the input. Can’t really do that with the pages themselves, but maybe there’s something there? Noticed `.rstrip()` in the Goose object’s dir. Is it applied directly to anything?

**Comment by barrust** [comment]
@Enkerli The second issue (throwing the 404 exception) is due to that is the response from the server. It is returning a 404 error on the 'https://cyberwales.net/clusters/' page. There are differences between python-goose and goose3 that changes the behavior of the page pull. Namely, goose3 uses the requests library which throws the exception. 

You can turn off the exception for the page pull by setting the strict configuration option: 

``` python
g=Goose({'strict': False})
article=g.extract('https://cyberwales.net/clusters/')
print(article.cleaned_text)
```

Hope this helps

**Comment by barrust** [comment]
Looking at the other issue I found that there are two different things happening: 

1. The page has several images that are no longer available which throws the Network 404 error by requests. I suspect that this is an older page and that is why the files are no longer available. You can bypass the missing images by setting either the `strict` or `enable_image_fetching` configuration options to False.
2. Without the correct `known_context_pattern` it is choosing the paragraph about the cookies as the most likely result. Not sure why that would be, but there it is. 

I also took a look at the html file and found another `known_context_pattern` that could be used: 
``` python
g = Goose({'strict': False})
    # g.config.known_context_patterns = {'attr': 'class', 'value': 'datos_caso'}
    g.config.known_context_patterns = {'attr': 'id', 'value': 'contenido_contacto'}
    print(g.config.known_context_patterns)
    article = g.extract(url='http://www.incyde.org/casos-exito/1')
    print(article.cleaned_text)
```

**Comment by lababidi** [comment]
Should we consider setting the strict and image_fetch to False as defaults?

**Comment by barrust** [comment]
I personally set enable_image_fetching to False for my own systems. I like having strict on, but that is a personal preference.

**Comment by Enkerli** [comment]
The two tips did help a bit for my specific case. Thanks a lot for these. 

The known context patterns are still causing some weirdness. Tried scraping that [whole site](http://www.incyde.org/) with diverse tags added as known context patterns. Some pages work with one context, others with another context. The key problem is, some pages stop working when two of these contexts are both added to the same list. In other words, some pages give me content from id `contenido_contacto` and others from id `contenido_ficha_curso`. If both context patterns coexist, some of these pages aren’t extracted properly. Which means that adding a bunch of class/id selectors doesn’t solve the problem.
(Also tried with ids `main-container2` and `centro_actualidad`, as well as classes `centrar`, `pr-xs-20`, and `col-lg-12`.)
Eventually stopped working on this problem, but wouldn’t say it’s a solved issue.
