### ISSUE TITLE
article = g.extract(raw_html=urls_content)  hangs for some html files

### ISSUE THREAD

**Issue by kochkinaelena** [goose3/goose3#36]
```
from goose3 import Goose
g = Goose()
article = g.extract(raw_html=urls_content) 
```

I have a bunch of html files and g.extract hangs indefinitely without crashing for some of them, but works fine for others. What could be the reason for this behaviour?

**Comment by barrust** [comment]
@kochkinaelena thank you for opening this issue. 

Can you tell us more about the files that are hanging? Or better, share one with us? Off the top of my head I don't know why they would be hanging. Something to try would be to turn off image pulling in the configuration. Note that image pulling will be off by default after the next release. 

``` python
from goose3 import Goose
g = Goose({'enable_image_fetching': False})
article = g.extract(raw_html=urls_content) 
```

**Comment by kochkinaelena** [comment]
This seems to have helped! Thank you!

Best,
Elena

**Comment by barrust** [comment]
Great! I am glad that helped out. If everything is working, can we close the issue? Thanks!

**Comment by ma-ji** [comment]
Hi, I got the same problem. You should be able to replicate it by this line:

```
results=g.extract(url='https://gist.githubusercontent.com/ma-ji/2dd9689a01c48bf7323b89d4e6b927d5/raw/21f680df041c9816d9d80faa4af599aa90df90be/raw_html.html')
```

Image fetching is disabled.

Thanks for helping!
