### ISSUE TITLE
Can't supress image error using try-catch

### ISSUE THREAD

**Issue by guiscaranse** [goose3/goose3#42]
So, I am getting the following error in my project, I don't really care about images or something, but I JUTS CAN'T supress this with a try catch thing. Any ideas why this happen?

`File not found
Traceback (most recent call last):
  File "C:\Users\User\.virtualenvs\project-1BJbA-LY\lib\site-packages\goose3\utils\images.py", line 45, in get_image_dimensions
    with Image.open(img_file) as image:
  File "C:\Users\User\.virtualenvs\project-1BJbA-LY\lib\site-packages\PIL\Image.py", line 2585, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BufferedReader name='C:\\Users\\User\\AppData\\Local\\Temp\\goose\\5de85086e98ea2edb5768554ace1d540.1523052502.29717_193e86f76a27012d6904aaacc8290000'>`

**Comment by guiscaranse** [comment]
Disabling `enable_image_fetching` stops throwing the error. But when its on try-catch can't detect the exception. Is something that you guys should take a look at.

**Comment by guiscaranse** [comment]
Ok, Image errors aren't the only one, `Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER` is being printed in shell every time that I use goose.

**Comment by barrust** [comment]
@guiscaranse could you provide example code where this issue is happening? Also, which version of goose3 are you using?

**Comment by barrust** [comment]
this should be resolved in #43
