### ISSUE TITLE
GooseImage

### ISSUE THREAD

**Issue by lababidi** [goose3/goose3#49]
@barrust thank you for your help with all this work. The community owes you a beer or ten. I've not been available to work on goose much, mostly because I'm not using it. 

As an architectural design plan, do you think creating a separate module/library to parse out images would be beneficial for separating the focused energy on the image along with focused energy on the text? Or do you think just creating a submodule would suffice? it seems that many of the issues i've seen are arising from image parsing.

**Comment by barrust** [comment]
I don't personally think it is necessary. We have set the `enable_image_fetching` to False. We are currently using PIL to do most of the work for the image processing. 

How do you think it would work if we split it out?

**Comment by lababidi** [comment]
I guess my initial thought is that it would be a module that would extract
all the images from a page. This way it can be expanded upon by other
developers and it would allow Goose to just focus on the text. Just a
thought.
