### ISSUE TITLE
Parse out article info from parsely-page tags

### ISSUE THREAD

**Issue by dlrobertson** [goose3/goose3#61]
See https://www.parse.ly/help/integration/ppage/. This isn't used as much now as the open graph protocol, but in the past it was used a lot more. As a result, this provides value to anyone using this library for parsing articles out of historical data e.g. the news crawl, common crawl, etc.

**Comment by barrust** [comment]
@dlrobertson do you have a live example of what this would be like in the wild? I would guess that it would be to find the `parsely-page' named meta tag and then serialize the json string (content) into a dictionary.

**Comment by barrust** [comment]
Thanks for the example. I will need to look into the `common crawl` I have never heard of it.

**Comment by dlrobertson** [comment]
The common crawl (http://commoncrawl.org/) and the news crawl (http://commoncrawl.org/2016/10/news-dataset-available/) might be relevant to this project. There might be some users of this project that use it to parse out articles and article metadata from pages one of the common crawl datasets.
