### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by dlrobertson** [goose3/goose3#65]
I typically like to reference the following guides:

 - [Mozilla Science Lab - Wrangling Web Contributions](https://mozillascience.github.io/working-open-workshop/contributing/)
 - [Open Source Guide - Writing Your Contributing Guidelines](https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines)

**Comment by barrust** [comment]
Would something like [this](https://github.com/barrust/mediawiki/blob/master/CONTRIBUTING.md) work? It is from another project of mine but I could easily convert it for goose3.
