### ISSUE TITLE
og_type does not currently support values with a subset

### ISSUE THREAD

**Issue by dlrobertson** [goose3/goose3#84]
## Description

If the og_type is one of [music](http://ogp.me/#type_music) or [video](http://ogp.me/#type_video) the `og_type` will include a subtype. For [video](http://ogp.me/#type_video), the `og_type` will be something like `video.movie`, `video.episode`, `video.tv_show`, or `video.other`. The type specific tags will not be preceded by `video.<subtype>:`, but instead will be prefixed by the normal `video:` string.

## Proposed change

The `og_type` parsing should populate the string used to search for additional tags with only the `og_type` up to the first `.`.

**Comment by barrust** [comment]
resolved by #90
