### ISSUE TITLE
Encoding Problem for some website?

### ISSUE THREAD

**Issue by apptech-evan-huang** [goose3/goose3#88]
```python3
from goose3 import Goose
from goose3.text import StopWordsChinese

g = Goose({'stopwords_class': StopWordsChinese})
url = 'http://hk.on.cc/hk/bkn/cnt/finance/20181010/bkn-20181010171513386-1010_00842_001.html'
article = g.extract(url=url)
print(article.title)
print(article.cleaned_text)
print(article.meta_description)
```

When I open this website in Chrome, the web page looks fine.

**Comment by barrust** [comment]
It is pulling the response in the "correct" encoding, per the HTML which says that it is/should be UTF-8. What should the proper encoding be?

**Comment by apptech-evan-huang** [comment]
After some research, I think the web page use UTF-8 indeed.

I tested using Chrome Console:
`document.characterSet` which output `UTF-8`

I also use https://nlp.fi.muni.cz/projects/chared/ to detection the charset.
It says both the detection result of specified by document are `utf_8`.

I also use `curl http://hk.on.cc/hk/bkn/cnt/finance/20181010/bkn-20181010171513386-1010_00842_001.html` to print the result to the console. The display also looks fine.

I also test `requests` on this page:
```python
import requests
r = request.get('http://hk.on.cc/hk/bkn/cnt/finance/20181010/bkn-20181010171513386-1010_00842_001.html')
print(r.text)
# !!!wrong content!!!
```

```python
import requests
r = request.get('http://hk.on.cc/hk/bkn/cnt/finance/20181010/bkn-20181010171513386-1010_00842_001.html')
print(r.encoding)
# ISO-8859-1
``` 

```python
import requests
r = requests.get('http://hk.on.cc/hk/bkn/cnt/finance/20181010/bkn-20181010171513386-1010_00842_001.html')
r.encoding = 'utf-8'
print(r.text)
# Correct content!
```

I think the problem is that `requests` cannot get the encoding from HTTP header so it uses the default `ISO-8859-1`. However, for `Goose`, it can know the actual encoding because it is specified in the HTML meta tag. Maybe you can change the response's encoding accordingly before parsing the HTML content?
