### ISSUE TITLE
Problem of text extraction from http://www.legorafi.fr/

### ISSUE THREAD

**Issue by Popotc** [goose3/goose3#99]
I am using your library to extract the text of French articles. I have a problem with the articles from http://www.legorafi.fr/. Goose extracts a text but it is not the text of the article we can read on the web. It extracts a hidden text in the source code of the page.

For instance, the text extracted by Goose3 for the page http://www.legorafi.fr/2018/12/05/une-video-dun-elevage-de-porc-lui-fait-prendre-conscience-quil-lui-reste-un-delicieux-pot-de-rillettes-dans-son-frigo-a-terminer/ is:
"N’est-ce pas la souffrance de l’animal qui donne à la viande son goût inimitable ? Comme si les larmes de l’animal constituaient une sauce tendre et douce !

 Pour mémoire, c’est depuis que les animaux sont élevés industriellement que la viande est devenue tendre. Elle a certainement moins de goût, mais convenons du fait qu’un taureau de corrida doit mariner une semaine avant de devenir accessible aux dents humaines ; une semaine c’est long !"

**Comment by Popotc** [comment]
Thank you very much for your answer!

**Comment by barrust** [comment]
Not a problem!
